### ISSUE TITLE
Добавить Devise

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#1]
# Мотивация

Для Аутентификации и авторизации установить гем Devise
# Описание

Установить гем Devise и указать чтобы он создал модель для User, и для девайся сделать небольшую кастомизацию в файел add_devise_to user
# Критерии приемки

Допустим я залогинился 
Если данные верны
То Вижу мое имя например в навбар
# планируемое время

0.5 часа

**Comment by yorc13** [comment]
Затраченное время 15 мин
