### ISSUE TITLE
При создании course element. Element type должен выбираться из списка

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#10]
# Мотивация
Необходимо сделать выпадающий список с типом занятия.

# Описание
Сейчас есть текстовое поле для добавления типа. Необходимо добавить 4 типа занятия (лекция, лабораторная, вебинар, контрольная) и сделать их выпадающим списком.

# Критерии приемки
Допустим мы создаем элемент курса
Если я захожу в форму создания элемента
То я вижу выпадающий список

# Оценочное время 1 час

**Comment by NurlanNur** [comment]
затрачено времени 30 мин
