### ISSUE TITLE
Необходимо добавить гем Paranoia

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#10]
# Мотивация

Необходимо сделать псевдо удаление элементов наших таблиц 
# Описание

В проекте нужно сделать чтобы при удалении какой-то сроки в какой-то таблице, эта строка не удалялась полностью, а как то скрывалась
# Критерий приемки

Допустим я преподаватель
Если я удалил какую-то тему курса
То при просмотре тем курса я вижу что тема удалилась, т.е не отображется в списке тем или элементов курса, но также если я администратор то я могу зайти в базу данных и увидеть там список всех тем или элементов курса даже удаленные
# оценочное время

1 час

**Comment by Reedlee** [comment]
Потратил 1,50минут
