### ISSUE TITLE
Перевести текст во вьюшках и облагородить кнопки

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#11]
# Мотивация

Необходимо чтобы вьюшки были русифицированы
# Описание

В проекте необходимо чтобы все вьюшки были максимально русифицированы
# Критерий приемки

Допустим я зашел под Админом  на список Курсов Courses
Если я смотрю на действия
То вижу что пишет правка или отредактировать и удалить, вместо edit, delete
Также вместо Courses#index,
Find me in app/views/courses/index.html.erb, вижу Курсы или Список Курсов, ну итд
# оценочное время

0.5 часа

**Comment by yorc13** [comment]
Затраченное время 1час

**Comment by Reedlee** [comment]
Затратил 15 минут
