### ISSUE TITLE
Добавить логирование действий/изменений

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#12]
# Мотивация
Необходимо сделать логирование всех действий пользователей для того чтобы всегда можно было отследить их действия.

# Описание
Логирование можно сделать через гем audited или поискать любое другое решение

# Критерии приемки
Допустим я захожу в раздел курсов или элементов курсов
Если я произвожу какое нибудь действие (редактирование или удаление) над курсами или элементами курсов
То в базе создается запись с последним действием

# Оценка времени 3 часа

**Comment by farid-92** [comment]
Затрачено 45 минут
