### ISSUE TITLE
Руссификация админки

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#13]
# Мотивация
Необходимо руссифицировать админку

# Описание
админку ActiveAdmin можно руссифицировать через гем i18n

# Критерии приемки
Допустим я захожу в админку
Если я вижу пункты меню, фильтры, кнопки
То они все на русском языке

# Оценка времени 2 часа

**Comment by NurlanNur** [comment]
затрачено времени 30 мин
