### ISSUE TITLE
Добавить редактор текста

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#13]
# Мотивация

Нужна возможность добавить учебный материал с возможностью его распечатать
# Описание

Найти гем для редактирования текста в онлайн режиме
Установить и настроить гем
Добавить на странице course-element таблицу со всем раздаточный материалом, который можно просмотреть, отредактировать, удалить
На этой же странице я могу добавить новый раздаточный материал
# Как проверить

Допустим я СуперАдмин и зашёл на страницу любого course_element
Если материал есть для этой страницы
То я вижу таблицу со списком материала и кнопки просмотреть, добавить, удалить

Допустим я зашёл на любую страницу course_element и  вижу таблицу со списком раздаточного материала
Если я нажимаю просмотреть
То у меня открывается страница предпросмотра, с которой я могу распечатать весь текст

Допустим я зашёл на любую страницу course_element и  вижу таблицу со списком раздаточного материала
Если я нажимаю редактировать
То я перехожу на другую страницу, в которой есть панель для редактирования текста, кнопка сохранения и кнопка возврата текста

Допустим я зашёл на любую страницу course_element и  вижу таблицу со списком раздаточного материала
Если я нажимаю удалить
То удаляется из таблицы строка, а в базе у материала становится статус удаленный
# планируемое время 9 часов

**Comment by Reedlee** [comment]
- Добавить псевдо удаление при удаление раздаточного материала к course_element

**Comment by farid-92** [comment]
Затрачено 6 часов, пока не работает печать, будет перенесен в другой тикет
