### ISSUE TITLE
Убрать при создании элемента курса список курсов

### ISSUE THREAD

**Issue by yorc13** [ESDP-15-5/student-crm#14]
#Мотивация
Необходимо убрать выпадающий список курсов при создании элемента, так как это не логично, он итак создается внутри текущего курса

# Описание
Убрать выпадающий список с выбором курса при создании элемента курса

# Критерии приемки
Допустим я захожу в курс
Если я нажимаю создать элемент курса
То я не вижу выпадающего списка с выбором курсов

# Оценка времени 0.5 часа

**Comment by farid-92** [comment]
Затрачено 20 минут
