### ISSUE TITLE
Добавить возможность прикреплять файлы к course_element

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#14]
# Мотивация

Нужно загружать доп материал для элемента курса. Н-р, шаблонные проект(zip) или картинки
# Описание

Создать модель для прикрепления файлов
Модель Course_element связана с моделью прикреплённые файлы один ко многим
Добавить возможность загрузить файл на странице course_element
Показывать таблицу со списком всех прикреплённых файлов
Добавить возможность удалить файл и скачать его не переходя со страницы
# Как проверить

Допустим я зашёл на любую страницу course_element и  вижу кнопку закачать новый файл
Если я нажимаю закачать
То я перехожу на страницу с формой название файла и закачаттьновый материал к данному элементу

Допустим я зашёл на любую страницу course_element и  вижу таблицу со списком прикреплённых файлов
Если я нажимаю скачать
То у меня открывается popup окно с выбором места сохранения файла
# Планируемое время 5 часов

**Comment by Reedlee** [comment]
Для работы с файлами достаточно: создание, чтение(скачать файл) и удаление.

**Comment by Reedlee** [comment]
я затратил 1 час над данным тикетом

**Comment by Reedlee** [comment]
- Для работы с файлами достаточно: создание, чтение(скачать файл) и удаление.
- Добавить псевдо удаление

**Comment by farid-92** [comment]
Затрачено 4 часа в офисе и 2 часа дома
