### ISSUE TITLE
Не работает создание пользователя(User)

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#15]
# шаги воспроизведения

Если зайти на вкладку users и заполнить форму, нажать сохранить
# наблюдаемое поведение

После нажатия сохранить, оказывается на пустой странице с путем .../users
# ожидаемое поведение

После нажатия сохранить
Должна появится запись в базе данных с указанием 
Email, password
И редирект на страницу  .../users/index 
С таблицей всех users
# экземпляр (версия ПО, окружение), в котором был обнаружен дефект
# сценарий тестирования

Допустим я открыл форму User
Если я нажму  кнопку сохранить
То происходит ридерект на страницу с таблицей всех  User и я там должен увидеть строку с внесёнными ранее данными
# планируемое время 1час

**Comment by NurlanNur** [comment]
40 мин

**Comment by NurlanNur** [comment]
- 5 мин
