### ISSUE TITLE
Добавить кнопку "Добавить элемент курса" в Course show

### ISSUE THREAD

**Issue by yorc13** [ESDP-15-5/student-crm#15]
# Мотивация
Необходимо добавить кнопку "Добавить элемент курса"

# Описание
Необходимо добавить кнопку "Добавить элемент курса" в course Show, которая будет создавать новый элемент курса. Внутри элемента курса автоматически будет заполняться название текущего курса.

# Критерии приемки
Допустим мы зашли в Courses выбрали курс
Если мы нажмем на кнопку добавить элемент курса
То мы увидим форму нового элемента курса с заполненым полем текущего курса.

# Оценка времени 2.5 часа

**Comment by farid-92** [comment]
Затрачено 20 минут
