### ISSUE TITLE
добавить возможность изменения порядка course_element

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#16]
# Мотивация

Для удобства сортировки тем занятий
# Описание

Найти гем, реализующий эту фичу (drag and drop), или же разобраться как использовать js
Провести настройку и добавление функционала
Расположение строк должно запоминается. Менять положение может СуперАдмин или Учитель 
# Как проверить

Допустим я зашёл на страницу конкретного курса 
Если я нажал на course_element
То он выделится его строку

Допустим я выделил строку
Если я потяну его вверх или вниз
То она будет вклиниваться между двумя другими строками

Допустим я вышел со страницы
Если я зайду на неё
То я увижу последний отредактированный порядок строк
# Планируемое время 5 часов

**Comment by NurlanNur** [comment]
затрачено 7 часов
