### ISSUE TITLE
Для демонстрации клиенту заполнить контентом курсы и элементы курсов

### ISSUE THREAD

**Issue by yorc13** [ESDP-15-5/student-crm#17]
# Мотивация
Необходимо перед сдачей клиенту наполнить сайт примерным контентом

# Описание
Создать фикстуры для курсов и элементов курсов

# Критерии приемки
Допустим заходим на сайт
Если мы переходим в раздел курсов или элементов
То мы видим тестовый контент (HTML-курс, RoR-курс и и т.д)

# Оценочное время 0.5 часа

**Comment by NurlanNur** [comment]
затрачено времени 40 мин
