### ISSUE TITLE
Улучшение по дизайну

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#17]
- Добавить "Хлебные крошки" под шапку
- Пофиксить дизайн кнопок в шапке
- Поддержать стилистику и расположение кнопок
- Создать пользователя - добавить кнопку
- Добавить название элемента курса, к которому добавляется файл
- Увеличить отступы между шапкой,кнопкой, контентом - так как все сливается

**Comment by Reedlee** [comment]
- Заменить слово Edit на Изменить, Delete на Удалить
- Можно удалить из navbar кнопку, которая отображется, когда не залогинен пользователь - из-за ненадобностью

**Comment by Reedlee** [comment]
## Описание проблемы

При нажатии кнопки edit открывается форма с текущими данными, но кнопка для подтверждения имеет значение "Создать Элемент курса"

## Ожидание

Увидеть кнопку со значением "Изменить Элемент курса"

**Comment by Reedlee** [comment]
# Планируемое время 4 часа

**Comment by NurlanNur** [comment]
Затратил 3 часа на хлебные крошки и некоторые улучшения

**Comment by Reedlee** [comment]
кнопка "Назад" в таблице с раздаточным материалом

таблица с материалом такой же дизайн, как и у таблицы с элементами курса

заменить текст в pop up, который появляется при удалении course_element

**Comment by NurlanNur** [comment]
делал отступы для кнопок плюс удаление кнопки назад, плюс переименовка в отображении имен таблиц - 40 мин

**Comment by Reedlee** [comment]
Не отображать таблицы материалов и файлов, если их нет в course_element

**Comment by Reedlee** [comment]
над тикетом работал 40 минут

**Comment by NurlanNur** [comment]
Изменены названия кнопок при отображении таблицы элементов курса и добавлено расстояние между кнопок
затрачено 30 мин

**Comment by Reedlee** [comment]
Затратил 10минут

**Comment by NurlanNur** [comment]
на исправления в хлебных крошках ушло 20 мин

**Comment by farid-92** [comment]
Затратил 10 минут
