### ISSUE TITLE
Реализовать handler для гема sorterable

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#19]
## Проблема в наблюдаемых явлениях

Если нажать на всю строку, то она цепляется и тянется вверх или вниз. Таким образом можно случайно сместить порядок строк
## Факты неудобства при использовании функции системы

Можно при просмотре случайно поменять местами строки
## Предлагаемое решение проблемы.

Добавить значок и ограничить область, за которую можно перетаскивать строку

**Comment by farid-92** [comment]
Затратил 30 минут
