### ISSUE TITLE
Улучшить Навигацию по 

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#19]
# Проблема в наблюдаемых явлениях
Тяжело перемещаться назад из текущего положения
# Факты неудобства при использовании функции системы
если перешел из ` course ` в создание ` course_element ` и передумал его создавать, то нужно снова искать ` course ` в таблице ` courses `.
# Предлагаемое решение проблемы.
Добавить nested model для отображения "хлебные крошки"

# Планируемое время 1 час

**Comment by farid-92** [comment]
Затрачено 1.10 минут
