### ISSUE TITLE
Подготовить окружение, добавить и установить gem'ы, Devise, ActiveAdmin

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#2]
# Мотивация
	Админка должна быть через ActiveAdmin
	
# Описание
	Необходимо установить ActiveAdmin, Devise.
	

# Критерии приемки#
	Допустим я разработчик системы
	Если я клонирую проект и устанавливаю зависимости
	То в зависимостях есть ActiveAdmin и Devise

**Comment by farid-92** [comment]
Затрачено 20 минут
