### ISSUE TITLE
Удалить гем актив админ

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#20]
# Мотивация
Админка должна быть написана вручную 

# Описание

Необходимо выпилить из проекта гем актив админ и все что к нему относится

# Критерии приемки

Проект должен работать после удаления гем active admin и всех связей с ним, чтобы можно было начать реализовывать требования заказчика.

# Оценочное время
 3 часа

**Comment by Reedlee** [comment]
Ушло 1.3 час
