### ISSUE TITLE
Создать модель User, Role, Users_role

### ISSUE THREAD

**Issue by farid-92** [ESDP-15-5/student-crm#21]
# Мотивация

Для нашего проекта нужна модель User, Role и промежуточная модель User_role

# Описание

Нужно создать модель User с полями email, password
Нужно создать модель Role c полем status
Нужно создать промежуточную модель Users_role с полями user_id, role_id

# Критерии приемки

Увидеть в базе данных созданные модели

#Планируемое время
1 час

**Comment by yorc13** [comment]
поля email и password в модели user добавиться при интеграции с devise

**Comment by yorc13** [comment]
Затрачено времени 1 час
