### ISSUE TITLE
Создать функционал печать материала

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#23]
## Мотивация

Заказчику нужно распечатывать раздаточный материал, который хранится на сайте
## Описание

Находясь на странице с открытым материалом должна быть возможность распечатать данный материал
## Критерий приемки

Допустим я зологиненный пользователь и зашел на страницу с материало
Если я нажал на кнопку печать
То у меня сохраняется pdf файл, который я могу распечатать
# Планируемое время 3 часа

**Comment by farid-92** [comment]
Затратил 30 минут
