### ISSUE TITLE
Удалить из проекта модель Teacher

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#23]
# Мотивация

Для новой реализации проекта нам не нужна модель Teacher

# Описание

Так как статус Teacher будет заведен через модель Role то нет необходимости в модели Teacher

# Критерии приемки

Отсуствие модели Teacher в проекте и дальнейшая работоспособность проекта.

#Планируемое время
0.5 часа

**Comment by yorc13** [comment]
Затраченое время 19 минут
