### ISSUE TITLE
Тестирование ПО

### ISSUE THREAD

**Issue by farid-92** [ESDP-15-5/student-crm#25]
# Мотивация

Нам как разработчикам необходимо, тестировать приложение
# Описание

Создать тесты для проверки входа пользователя на сайт, создание курса,создание элемента курсов. добавление файла в элемент курса, добавление материалов
При запуске тестов, откроется окно браузера и выполнит клики,заполнения,отправку форм, вместо человека.
# Планируемое время 9 часов

**Comment by Reedlee** [comment]
Приступил к написанию теста для проверки входа пользователя на сайт
Затратил 2 часа

**Comment by Reedlee** [comment]
Затратил 2 часа 30 минут 11/12/2015

**Comment by Reedlee** [comment]
Затратил 3 часа 30 минут 12/12/2015

**Comment by Reedlee** [comment]
Затратил 3 часа на создание CRUD для course_element_file

**Comment by NurlanNur** [comment]
Затратил 10 часов 15 мин
