### ISSUE TITLE
Создание занятий

### ISSUE THREAD

**Issue by farid-92** [ESDP-15-5/student-crm#26]
# Мотивация

Для проверки работы календаря необходимо сначала создать занятие
# Описание

Создать контроллер Занятие
Добавить занятие и к нему привязать элемент курса. Связь один-ко-многим
Сделать CRUD занятий
# Критерии приемки

Допустим я зашел на вкладку Занятие,
Если я нажал на создание нового занятия
То у меня открывается pop up окно формы создания занятия
# Планируемое время 5 часов

**Comment by farid-92** [comment]
Затратил 3 часа

**Comment by yorc13** [comment]
Затратил 3 часа на CRUD и подключение аудит, паранойя
