### ISSUE TITLE
Создать CRUD для Группы

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#28]
## Мотивация

Необходимо на сайте иметь возможность создавать группы студентов. Это необходимо для реализации фильтрации календаря по группам
## Описание

В проекте нужно видеть список Групп и CRUD для различных действий. 
Пока группа имеет только связку с Course(много групп - один курс)
## Критерий приемки

Допустим я зашел залогинен под Админом
Если я захожу на вкладку группы из курса
То вижу список Групп к данному курсу
И кнопку на создание новой группы или удаления старой группы.

**Comment by farid-92** [comment]
Затрачено 30 минут

**Comment by yorc13** [comment]
На прикручивание аудита и паранойи ушло 15минут
