### ISSUE TITLE
Добавить форматирование календаря

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#29]
## Мотивация

Дополнительно нужна возможность наглядно отображать календарь по группам и типам занятий  
## Описание

В календарь можно попасть из курса. Зайдя на страницу с календарем для удобства отображения нужно, чтобы для каждого типа занятия отображалась своя иконка. При этом цвета групп между собой различались. Саму легенду групп/курсов нужно отображать сверху.
## Критерий приемки

Допустим я залогиненный пользователь
Если я перешел на страницу календаря
То у меня отобразятся занятия данного курса с разбивкой по группам
И они будут отличаться по цвету

**Comment by farid-92** [comment]
Затратил 5 часов на разбор полетов

**Comment by farid-92** [comment]
Затратил 1 час

**Comment by Reedlee** [comment]
Затратил 30 минут на значки

**Comment by NurlanNur** [comment]
Затратил 6 часов
