### ISSUE TITLE
Создать и добавить в АктивАдмин Courses и Course_element

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#3]
# Мотивация
		Клиенту необходимо создавать курсы и элементы курса из интерфейса админа.
		
# Описание
		Необходимо добавить в ActiveAdmin сущности курса и элемента курса
	
# Критерии приемки
		Допустим я залогинен как админ
		Если я захожу на страницу админа в раздел курсы,
		То я вижу кнопку "Создать курс" и ниже вижу таблицу курсов
		
		Допустим я залогинен как админ
		Если я захожу на страницу "Элементы курсов"
		То я вижу кнопку "создать элемент курса" и ниже вижу таблицу элементов курсов с указанием курса.

**Comment by farid-92** [comment]
Затрачено 40 минут. Разбирались с git'ом
