### ISSUE TITLE
Создать список Course(Курсов) и crud 

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#3]
# Мотивация

Необходимо на сайте видеть отображение всех Курсов
# Описание

В проекте нужно видеть например все курсы и CRUD  для различных действий
Отображать список Курсов в обратном порядке создания т.е от последнего созданного к первому созданному
# Критерий приемки

Допустим я зашел под пользователем  на список Курсов Course
Если не обходимо
То можно создать новый Курс, отредактировать его например изменив имя, или удалить существующий Курс
# оценочное время

1 час

**Comment by Reedlee** [comment]
Затратил 1 час
