### ISSUE TITLE
Создать список Course_elements и crud для него

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#4]
# Мотивация

Необходимо при входе в определенный Курс (Course) видеть элементы этого курса
# Описание

В проекте должны быть элементы курсов для соответсвующих Курсов
# Критерий приемки

Допустим я зашел под пользователем  на список Курсов Course
Если пользователь заходит в Course
То видит список элеметов курса тему элемента, тип элемента ну и actions
# оценочное время

1 час

**Comment by Reedlee** [comment]
В ушло классе 1 час 30 минут времени.
Дома затратил на решение 2 часа
