### ISSUE TITLE
Убрать удаление элементов и курсов. (для Логирования)

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#4]
# Мотивация 
Оставить Delete если найдем GEM или убирать Delete из CRUD если нет

# Описание
Найти Gem (Paranoia или другой), разобраться с ним и попробовать использовать для изменения статуса записей в базе с активной на удаленную, при этом не отображая их для всех

# Критерии приемки 
Допустим мы залогинены под админом
Если мы удаляем запись
То эта запись больше не отображается у всех, но остается в базе

**Comment by farid-92** [comment]
Затрачено 30 минут
