### ISSUE TITLE
Добавить удаление занятия в календаре

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#40]
# Мотивация

Чтобы при двойном клике на занятие, оно удалялось.
# Описание

На текущий момент, чтобы удалить занятие в каком то дне недели, мы нажимает на иконку корзины, по словам заказчика этот подход ему не очень подходит, поэтому надо реализовать возможность удаления занятия из календаря по двойному клику.
# Планируемое время 3 часа

**Comment by Reedlee** [comment]
Ушло 2 часа
