### ISSUE TITLE
Изменить редактирование занятия в календаре 

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#41]
# Мотивация

При одинарном клике на плашке занятия, добавить возможность его редактирования
# Описание

На текущий момент, чтобы отредактировать занятие, надо кликнуть непосредственно линк занятия в виде текста, по пожеланию заказчика
необходимо реализовать функционал при котором при одинарном клике на любом месте плашки нужного занятия, перекидывало на форму редактирования этого занятия
# Планируемое время 3 часа

**Comment by Reedlee** [comment]
Затратил 1 час
