### ISSUE TITLE
Изменить отображение лэйбла занятия в календаре

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#42]
# Мотивация

Необходимо при отображении плашки для занятия, видеть время его проведения.
# Описание

На момент написания этого тикета, в плашке занятия есть иконка типа занятия, название группы, корзина для удаления занятия, название занятия, необходимо вместо иконки удаления занятия, отобразить время его проведения
# Планируемое время 3 часа

**Comment by Reedlee** [comment]
затратил 36 минут
