### ISSUE TITLE
По клику заполнять время формы

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#43]
# Мотивация

Необходимо при клике на пустом месте дня календаря частично заполнять форму
# Описание

Заказчик хочет чтобы, при клике на дне календаря в не заполненом месте, создавалось занятие, при этом в форме создания занятия необходимо чтобы из этого дня бралась дата и автоматически вставлялась в форму, также при этом, время по-умолчанию  ставилось 19,00
# Планируемое время 3 часа

**Comment by Reedlee** [comment]
1 час  12 февраля
2 часа 40 минут 14 февраля

**Comment by Reedlee** [comment]
затратил 15 минут сегодня
