### ISSUE TITLE
Изменить удаление занятия в календаре

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#46]
# Мотивация

Необходимо удалять занятие по клику иконки корзины во всплывашке
# Описание

Нужно сделать чтобы занятие удалялось при нажатии на иконку корзины, которая будет отображаться во всплывающем окне (popover), при этом необходимо чтобы всплывашка оставалась видимой бесконечно, если мышка находится на плашке
# Планируемое время 3 часа

**Comment by Reedlee** [comment]
затратил 1 час 30 минут
