### ISSUE TITLE
Создать список пользователей Users и CRUD 

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#5]
# Мотивация

Необходимо на сайте видеть отображение всех Курсов
# Описание

В проекте нужно видеть список Пользователей и CRUD  для различных действий
# Критерий приемки

Допустим я зашел под Админом  на список Пользователей Users
вижу список всех пользователей
Если не обходимо
То можно создать нового Пользователя, отредактировать его например изменив имя, фамилию, или удалить
# оценочное время

1 час

**Comment by Reedlee** [comment]
Затратил 1 час
