### ISSUE TITLE
Создать модель препод ТОЛЬКО для фикстуры (для фильтрации)

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#5]
# Мотивация
		Необходимо создать сущность препод
	
# Описание
		Нужно создать модель Препод с полями first name, last name, phone, email
		У препода может быть несколько элементов курса
		Также необходимо создать фикстуры для модели Препод.
		Препод не обязателен для элемента курса
	
# Критерии приемки
		Допустим я захожу под админом
		Если перехожу в элементы курсы
		То вижу выпадающий список преподавателей напротив элементов курсов для выбора преподавателя

**Comment by NurlanNur** [comment]
затрачено времени 40 мин
