### ISSUE TITLE
Редизайн сайта

### ISSUE THREAD

**Issue by farid-92** [ESDP-15-5/student-crm#58]
# Мотивация

На данный момент дизайн сайта слабоват
# Описание

Заказчику не понравился дизайн сайта. Поэтому изменить дизайн для удобства использования.
# Планируемое время

**Comment by Reedlee** [comment]
затратил 11 февраля 30минут

**Comment by Reedlee** [comment]
На данный момент закрываем из-за того, что проект уже сдали заказчику.
