### ISSUE TITLE
Добавить гем Bootstrap

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#6]
# Мотивация

Добавить гем bootstrap
# Описание

Необходимо оформлять вьюшки при помощи bootstrap
# Критерий приемки

Допустим я зашел под пользователем  
Если если захожу на список курсов 
То вижу красивый список оформленный например с помощью bootstrap
# оценочное время

0.5 часа

**Comment by Reedlee** [comment]
Потратил 5 минут

**Comment by Reedlee** [comment]
Еще 5 минут на доподключение в главный layout
