### ISSUE TITLE
Модуль оценки домашних заданий и коментарии

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#64]
# Мотивация

Нужно чтобы была возможность оценивать домашние задания
# Описание

Необходимо разработать логику, при которой можно было бы оценивать домашние задания студентов,  и оставлять коментария к домашним заданиям
# Планируемое время 4 часа

**Comment by Reedlee** [comment]
Комментарий к 52 занятию по ссылке
https://github.com/ESDP-15-5/student-crm/commit/428d68c867d5f9ae1633aaba49738550022728ca
Содержит в себе модальные формы для оценки и написания комментариев

**Comment by Reedlee** [comment]
Затратил 2 часа
