### ISSUE TITLE
В поле учитель отображается id объекта вместо ФИ

### ISSUE THREAD

**Issue by Reedlee** [ESDP-15-5/student-crm#8]
# Мотивация
Необходимо исправить отображение ФИ в поле учитель

# Описание
Исправить отображение ФИ учителя, в данный момент при переходе в фильтр или при создании преподавателя в поле учитель выпадающий список состоял из id объектов.
Техническое решение: Переопределить метод to_s в модели учитель

# Критерии приемки
Допустим мы переходим на создание преподавателя
Если мы нажимаем на выпадающий список
То мы видим ФИ преподавателей

# Оценочное время: 1 час

**Comment by farid-92** [comment]
Затрачено 30 минут
