### ISSUE TITLE
Создать Navbar для регистрации и входа на сайт и пр.

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#8]
# Мотивация

Необходимо чтобы у нас в прокте была навигационная панель
# Описание

Нужно создать навигационную панель для входа на сайт,  перехода по каким то менюшкам,
например создать кнопки курсы Courses, пользователи Users, кнопку для регистрации нового пользователя на данный момент можно скрыть
# Критерий приемки

Допустим я зарегестрированный пользователь 
Если я захочу за логинится
То можно можно посмотреть на навигационную панель увидеть там кнопку log in или войти нажать на нее ввести данные в форму и зайти под собой при этом отображется соообщение об успешном входе
# оценочное время

1 час

**Comment by Reedlee** [comment]
Затратил 1,30 минут

**Comment by Reedlee** [comment]
Затратил 19 минут. Были проблемы с гитом
