### ISSUE TITLE
Необходимо сделать базовую авторизацию

### ISSUE THREAD

**Issue by NurlanNur** [ESDP-15-5/student-crm#9]
# Мотивация

Заказчик не хочет, чтобы не залогиненные пользователи не имели доступ к страницам отличным от root
# Описание

Если пользователю создан аккаунт, то он имеет права СуперАдмина
# Критерий приемки

Допустим я не залогиненный пользователь
Если я ввёл в адресную строку любой другой путь отличный от root_path
То меня редиректит на root_path

Допустим я зашёл на root_path 
Если  я залогинился
То мне доступны все страницы и все права на CRUD
# оценочное время

1 час

**Comment by Reedlee** [comment]
Затратил 10минут
